import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar";

//getting the current route only woks in client server
// import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

//Title of the website
export const metadata: Metadata = {
  title: {
    default: "Next App",
    template: "%s | Next App",    
  },
  description: "Generated by create next app",
  
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const dummy="dummy";
  return ( 
    <html lang="en" data-theme="light">
      <body className={inter.className}>

        {/* <Container></Container> */}
        
        {/* <Header/> */}
        <Navbar/>
        {children}
        {/* <Footer/> */}

      </body>
    </html>
  );
}
